I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenarios/scenario_2.rpy", line 33, in script
    classmate_1 "Teacher, what topic will our group be working on?"
Exception: Sayer 'classmate_1' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenarios/scenario_2.rpy", line 33, in script
    classmate_1 "Teacher, what topic will our group be working on?"
  File "/Users/joworld/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/joworld/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/joworld/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'classmate_1' is not defined.

macOS-15.3.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
myself_2 1.0
Sun Mar 23 10:06:09 2025
